[package]
name = "NetCAT"
version = "0.1.0"
authors = ["Neve Noomo <d3ad.l1n3@yandex.ru>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ibverbs = {git = "https://github.com/jonhoo/rust-ibverbs", rev="9b06dbc23488f48f12e26693318e90b7003e9a89"}
rand = "0.7.2"

[dev-dependencies]
criterion = "0.3.0"

[[bench]]
name = "rpp_bench"
harness = false

# [[bench]]
# name = "naive_rpp_bench"
# harness = false

[profile.bench]
opt-level = 3
lto = true